# Generated by Django 4.1 on 2022-08-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloCarro', models.CharField(max_length=20, verbose_name='Título')),
                ('precoCarro', models.IntegerField(verbose_name='Preço')),
                ('anoCarro', models.IntegerField(verbose_name='Ano de fabricação')),
                ('marcaCarro', models.CharField(max_length=20, verbose_name='Marca')),
                ('combustivelCarro', models.CharField(max_length=20, verbose_name='Combustível')),
                ('tipoCarro', models.CharField(max_length=20, verbose_name='Tipo')),
                ('created_atCarro', models.DateTimeField(auto_now_add=True)),
                ('updated_atCarro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloMoto', models.CharField(max_length=100, verbose_name='Título')),
                ('precoMoto', models.IntegerField(verbose_name='Preço')),
                ('anoMoto', models.IntegerField(verbose_name='Ano de fabricação')),
                ('marcaMoto', models.CharField(max_length=20, verbose_name='Marca')),
                ('combustivelMoto', models.CharField(max_length=20, verbose_name='Combustível')),
                ('tipoMoto', models.CharField(max_length=20, verbose_name='Tipo')),
                ('created_atMoto', models.DateTimeField(auto_now_add=True)),
                ('updated_atMoto', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
