# Generated by Django 4.1 on 2022-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_cpf_alter_user_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='Sexo'),
        ),
    ]
