# Generated by Django 4.1 on 2022-08-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
