# Generated by Django 4.1 on 2022-08-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='combustivelMoto',
            field=models.CharField(blank=True, choices=[('G', 'GASOLINA'), ('F', 'FLEX'), ('D', 'DIESEL')], max_length=1, null=True, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='tituloMoto',
            field=models.CharField(max_length=20, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
