# Generated by Django 4.1 on 2022-08-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_moto_combustivelmoto_alter_moto_titulomoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='combustivelCarro',
            field=models.CharField(blank=True, choices=[('G', 'GASOLINA'), ('F', 'FLEX'), ('D', 'DIESEL')], max_length=1, null=True, verbose_name='Combustível'),
        ),
    ]
