# Generated by Django 4.1 on 2022-08-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_carro_combustivelcarro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='combustivelCarro',
            field=models.CharField(blank=True, choices=[('GASOLINA', 'GASOLINA'), ('FLEX', 'FLEX'), ('DIESEL', 'DIESEL')], max_length=8, null=True, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='combustivelMoto',
            field=models.CharField(blank=True, choices=[('GASOLINA', 'GASOLINA '), ('FLEX', 'FLEX '), ('DIESEL', 'DIESEL ')], max_length=8, null=True, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
    ]
