# Generated by Django 4.1 on 2022-08-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(max_length=2, verbose_name='Idade'),
        ),
    ]
