# Generated by Django 4.1 on 2022-08-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
    ]
